export const INITIAL_PRODUCTS = [
  {
    "id": 1,
    "title": "Captiva Ocean Azure Wall",
    "category": "Wall Tiles",
    "categoryType": "DIGITAL WALL TILES",
    "ethnicity": "Heritage & Aquatic Concept",
    "finish": "Glossy",
    "material": "Ceramic",
    "netQuantity": "6 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "300x450 mm, 600x1200 mm, 600x600 mm",
    "price": 68,
    "oldPrice": 78,
    "inStock": true,
    "image": "/tiles/tile_1.jpg",
    "description": "Aquatic themed digital ceramic wall tile featuring serene underwater and cloud motifs with a brilliant high-gloss protective glaze. Ideal for bathrooms and kitchen splashbacks."
  },
  {
    "id": 2,
    "title": "Luxe Cuba Selva",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Tropical Exotic Green",
    "finish": "Matt Carving",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 98,
    "oldPrice": 115,
    "inStock": true,
    "image": "/tiles/tile_2.jpg",
    "description": "Exquisite forest green marble slab with organic golden mineral veins in a tactile Matt Carving finish. Delivers an organic architectural statement to luxury interior floors."
  },
  {
    "id": 3,
    "title": "Supera Bianco Statuario",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Classic Italian Carrara",
    "finish": "Polished Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 94,
    "oldPrice": 110,
    "inStock": true,
    "image": "/tiles/tile_3.jpg",
    "description": "Iconic Italian Statuario marble pattern featuring bold feathered grey veining over an ultra-pure white vitrified porcelain body with a mirror-reflection polish."
  },
  {
    "id": 4,
    "title": "Vizio Blue Ocean",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Mediterranean Ocean Blue",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 105,
    "oldPrice": 125,
    "inStock": true,
    "image": "/tiles/tile_4.jpg",
    "description": "Deep Mediterranean blue glazed vitrified tile infused with swirling crystalline onyx veins. Creates dramatic accent walls, grand foyers, and commercial statement spaces."
  },
  {
    "id": 5,
    "title": "Vibrato Royal Gold",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Royal Persian Vein Onyx",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 112,
    "oldPrice": 130,
    "inStock": true,
    "image": "/tiles/tile_5.jpg",
    "description": "Opulent Persian-inspired golden onyx with multi-layered honey amber veins and crystal depth. Engineered for high-traffic luxury residential living rooms and suites."
  },
  {
    "id": 6,
    "title": "Luxe Logan Grey",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Nordic Minimalist Slate",
    "finish": "Matt Carving",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 92,
    "oldPrice": 108,
    "inStock": true,
    "image": "/tiles/tile_6.jpg",
    "description": "Subtle architectural slate grey with micro-carved texture lines offering an anti-glare, non-slip touch. Designed for contemporary modern villas and Scandinavian interiors."
  },
  {
    "id": 7,
    "title": "Scone Sky Blue",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Aegean Coastal Marble",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 96,
    "oldPrice": 112,
    "inStock": true,
    "image": "/tiles/tile_7.jpg",
    "description": "Breezy Aegean sky blue vitrified slab with flowing white wave ripples. Rejuvenates master bathrooms, spa areas, and modern open-plan living rooms."
  },
  {
    "id": 8,
    "title": "Influencer Gold Onyx",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Venetian Golden Onyx",
    "finish": "Mirror Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 118,
    "oldPrice": 138,
    "inStock": true,
    "image": "/tiles/tile_8.jpg",
    "description": "Regal Venetian gold marble slab with high-clarity translucent vein patterns. Highly resistant to stains and abrasion, ideal for luxury boutique showrooms and living lounges."
  },
  {
    "id": 9,
    "title": "Adreson Sapphire Blue",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Deep Ocean Azure Marble",
    "finish": "Mirror Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 108,
    "oldPrice": 128,
    "inStock": true,
    "image": "/tiles/tile_9.jpg",
    "description": "Intense sapphire and lapis veins interlocked with ivory fractures in a mirror polished finish. Elevates feature walls and premium flooring installations."
  },
  {
    "id": 10,
    "title": "Oviya Calacatta Crema",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Tuscan Warm Calacatta",
    "finish": "Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 89,
    "oldPrice": 105,
    "inStock": true,
    "image": "/tiles/tile_10.jpg",
    "description": "Warm Tuscan ivory base with subtle amber and caramel veins. Seamlessly coordinates with natural wood cabinetry and neutral architectural palettes."
  },
  {
    "id": 11,
    "title": "Amazone Blue River",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Amazonian River Stone",
    "finish": "Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 104,
    "oldPrice": 122,
    "inStock": true,
    "image": "/tiles/tile_11.jpg",
    "description": "Dramatic river-flow veining capturing the primal power of the Amazon river in aquatic blues and emerald mineral streaks. Exceptional optical depth."
  },
  {
    "id": 12,
    "title": "Silver Mist Slate",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Contemporary Urban Mineral",
    "finish": "Matt Carving",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 88,
    "oldPrice": 102,
    "inStock": true,
    "image": "/tiles/tile_12.jpg",
    "description": "Cool mineral grey slab with refined metallic mist graining and carving texture. Zero-light reflection, perfect for contemporary offices, corridors, and wet areas."
  },
  {
    "id": 13,
    "title": "Jorden Black Noir",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Spanish Marquina Black",
    "finish": "Mirror Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 115,
    "oldPrice": 135,
    "inStock": true,
    "image": "/tiles/tile_13.jpg",
    "description": "Jet black midnight slab traversed by sharp, striking lightning-white calcite veins. Delivers peerless grandeur to dining halls, luxury bathrooms, and boutique lounges."
  },
  {
    "id": 14,
    "title": "Goldwave Imperial",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Royal Dubai Imperial Onyx",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 128,
    "oldPrice": 150,
    "inStock": true,
    "image": "/tiles/tile_14.jpg",
    "description": "Rich undulating golden ribbon waves floating across an ivory-gold translucent stone bed. A premier luxury porcelain slab for high-end villas and penthouses."
  },
  {
    "id": 15,
    "title": "Evoke Beige Travertine",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Roman Warm Travertine",
    "finish": "Glossy Surface",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 86,
    "oldPrice": 100,
    "inStock": true,
    "image": "/tiles/tile_15.jpg",
    "description": "Soothing Roman travertine beige with horizontal sedimentary flow lines. Imparts a relaxed Mediterranean ambiance to living rooms, bedrooms, and terraces."
  },
  {
    "id": 16,
    "title": "Rembo Aqva Turquoise",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Maldives Lagoon Turquoise",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 102,
    "oldPrice": 120,
    "inStock": true,
    "image": "/tiles/tile_16.jpg",
    "description": "Luminous turquoise water crystal tones reminiscent of Maldivian lagoons. Creates vibrant feature backdrops in powder rooms, pool decks, and wellness centers."
  },
  {
    "id": 17,
    "title": "Orabella Endless Sinuous",
    "category": "Glazed Vitrified",
    "categoryType": "ENDLESS VEIN SLABS",
    "ethnicity": "Continuous Italian Bookmatch",
    "finish": "Endless Glossy",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 122,
    "oldPrice": 145,
    "inStock": true,
    "image": "/tiles/tile_17.jpg",
    "description": "Endless design technology where veins seamlessly continue tile after tile without breaks. Engineered for seamless expansive wall panels and infinite floor expanses."
  },
  {
    "id": 18,
    "title": "Mestrow Deep Blue",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Midnight Blue Lapis Lazuli",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 110,
    "oldPrice": 130,
    "inStock": true,
    "image": "/tiles/tile_18.jpg",
    "description": "Galaxy-inspired lapis lazuli navy with interstellar stardust flecks and dramatic cloud fractures. A true masterpiece of ceramic print engineering."
  },
  {
    "id": 19,
    "title": "Spyker Sky Crystal",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Arctic Ice Crystal",
    "finish": "Glossy Finish",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 95,
    "oldPrice": 112,
    "inStock": true,
    "image": "/tiles/tile_19.jpg",
    "description": "Prismatic glacial ice patterns with crystalline quartz veining in cool sky blue. Brings natural illumination and a feeling of boundless space to modern homes."
  },
  {
    "id": 20,
    "title": "Alpha Jade Green",
    "category": "Polished Vitrified",
    "categoryType": "POLISHED VITRIFIED TILES",
    "ethnicity": "Emerald Jadeite Stone",
    "finish": "Glossy Random",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 114,
    "oldPrice": 134,
    "inStock": true,
    "image": "/tiles/tile_20.jpg",
    "description": "Serpentine jade green marble with rich deep emerald gradients and olive mineral clusters. An ancient stone aesthetic revitalized through modern vitrification."
  },
  {
    "id": 21,
    "title": "Eternal Fornk Blue",
    "category": "Glazed Vitrified",
    "categoryType": "GLAZED VITRIFIED TILES",
    "ethnicity": "Royal Cobalt Marble",
    "finish": "High Gloss",
    "material": "Vitrified Slab",
    "netQuantity": "2 Pieces/Box",
    "brand": "Oviya Ceramics",
    "size": "600x1200 mm, 800x1600 mm, 1200x2400 mm, 800x800 mm, 600x600 mm",
    "price": 106,
    "oldPrice": 125,
    "inStock": true,
    "image": "/tiles/tile_21.jpg",
    "description": "Stately royal cobalt blue slab marked with silver thunderbolt veins. Highly sought after by interior architects for statement bar fronts and focal points."
  }
];
